<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.10 setup script
 * Date: Mon, 18 Jul 2022 05:32:54 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: 10.51.203.95 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '10.51.203.95';
$cfg['Servers'][$i]['host'] = '10.51.203.95';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'ukdr';
$cfg['Servers'][$i]['password'] = '123qwe!@#QWE';

/* End of servers configuration */

$cfg['blowfish_secret'] = '8Bn?jsL,McX^tI+D$kEBQRX|l\'t(1f]';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>